#!/usr/bin/env bash
t1="that story about zeldo"
t2="amorg"

files_in_order="
src/lib.lua
src/att.lua

src/chars.lua
src/outlines.lua
src/draw.lua
src/inventory.lua
src/inventory_selection.lua
src/map.lua
src/menu.lua
src/misc.lua
src/move_funcs.lua
src/squares.lua
src/tbox.lua
src/tcol.lua
src/title.lua
src/view.lua

src/map_data.lua
src/story.lua
src/parents.lua
src/acts/*
src/demo.lua
"

./pico_minifier -d $files_in_order > ._compiled.lua
