#!/bin/bash
cp zeldo.p8 .outline.p8
perl -0777 -pi -e '
my $doc = do {
    local $/ = undef;
    open my $fh, "<", "src/compile_outline.lua"
        or die "could not open file";
    <$fh>;
}; my $header = "'"-- $t1\n-- $t2"'";
s/(__lua__).*(__gfx__)/$1\n$header\n$doc\n$2/igs;
' .outline.p8

pico8 -x .outline > src/outlines.lua
sed -i '/RUNNING/d' src/outlines.lua
rm .outline.p8
