#!/usr/bin/env bash

files_in_order="
src/lib.lua
src/att.lua

src/chars.lua
src/draw.lua
src/inventory.lua
src/inventory_selection.lua
src/map.lua
src/menu.lua
src/misc.lua
src/move_funcs.lua
src/pattern.lua
src/squares.lua
src/story.lua
src/tbox.lua
src/tcol.lua
src/title.lua
src/view.lua

src/parents.lua
src/acts.lua
src/demo.lua
"

./pico_minifier -d $files_in_order > _compiled_dev.lua
./pico_minifier $files_in_order > _compiled_prod.lua
