#!/usr/bin/env bash
# Zeldo Map Builder
# By Alan Morgan

# First compile the map builder:
files_in_order="
src/lib.lua
src/att.lua

src/chars.lua
src/outlines.lua
src/draw.lua
src/inventory.lua
src/inventory_selection.lua
src/map.lua
src/menu.lua
src/misc.lua
src/move_funcs.lua
src/squares.lua
src/tbox.lua
src/tcol.lua
src/title.lua
src/view.lua

src/parents.lua
src/acts/*

src/map_data.lua
src/mapbuilder_demo.lua
"

./pico_minifier -d $files_in_order > _compiled_mapbuilder_dev.lua

# Now create the p8 file for the map builder.
cp zeldo.p8 .mapb.p8
perl -0777 -pi -e 's/(__lua__).*(__gfx__)/$1\n#include _compiled_mapbuilder_dev.lua\n$2/igs' .mapb.p8

# Next convert that pico8 file into a binary, so we can close out of it on save.
pico8 .mapb.p8 -export "-i 48 .mapb.bin"
.mapb.bin/linux/.mapb > .mapb.bin/tmp_map_data.lua

# Now write to the map data file if you hit save in your program.
OUTPUT=$(cat .mapb.bin/tmp_map_data.lua | tr -d "[:space:]")
if [ -z "$OUTPUT" ];
then
    echo "Program didn't output anything."
    echo "So... I'm not writing to src/map_data.lua"
else
    mv .mapb.bin/tmp_map_data.lua src/map_data.lua
    echo "Wrote map to 'src/map_data.lua'."
fi

# And finally some cleanup.
rm -r .mapb.bin
rm .mapb.p8
