#!/usr/bin/perl -Iminifier_lib/
use strict;
use warnings;
use experimental 'smartmatch';
use Alanxoc3::Pico8FormatUtil;
use Getopt::Long qw(GetOptions);

use utf8;
use open qw(:std :utf8);
binmode(STDIN, "encoding(UTF-8)");
binmode(STDOUT, "encoding(UTF-8)");

my $dev_mode;
my $ascii;
my $input_file = "";
my $output_file = "";
GetOptions('dev' => \$dev_mode, 'ascii' => \$ascii, 'input=s' => \$input_file, 'output=s' => \$output_file) or die "Usage: $0 [--dev] [--ascii] -i f -o f\n";

# Constants specific to Zeldo.
my %constants;

# Colors
$constants{'FG_YELLOW'} = '10';
$constants{'BG_YELLOW'} = '9';
$constants{'FG_WHITE'} = '7';
$constants{'BG_WHITE'} = '5';
$constants{'FG_RED'} = '8';
$constants{'BG_RED'} = '2';
$constants{'FG_GREEN'} = '11';
$constants{'BG_GREEN'} = '3';
$constants{'FG_UI'} = '13';
$constants{'BG_UI'} = '1';
$constants{'SL_UI'} = '2';
$constants{'BG'} = '0';

# Symbols
if (!$ascii) {
   $constants{'B_UP'} = '⬆️';
   $constants{'B_DOWN'} = '⬇️';
   $constants{'B_LEFT'} = '⬅️';
   $constants{'B_RIGHT'} = '➡️';
   $constants{'B_X'} = '❎';
   $constants{'B_O'} = '🅾️';
}

# Other
$constants{'FADE_TIME'} = '.5';
$constants{'MAX_ENERGY'} = '100';
$constants{'INTERACT_SPACE'} = '.5';
$constants{'FPS'} = '60';
$constants{'CART_NAME'} = '"zeldo_test5"';
$constants{'TEMP_SAVE_LOCATION'} = '0x5d00';
$constants{'REAL_SAVE_LOCATION'} = '0x5e00';
$constants{'SAVE_LENGTH'}        = '64';
$constants{'FIRST_ITEM_COST'} = '10';
$constants{'LANK_START_HEALTH'} = '10';

# Save states (up to 256).
$constants{'VERSION'}        = '0'  ;
$constants{'HARD_MODE'}      = '1'  ;
$constants{'SAVE_SPOT'}      = '2'  ;
$constants{'MONEY'}          = '3'  ; # Used
$constants{'HEALTH'}         = '4'  ;
$constants{'HAS_FORCE'}      = '5'  ; # Used
$constants{'HAS_BOOMERANG'}  = '6'  ; # Used
$constants{'HAS_BOMB'}       = '7'  ; # Used
$constants{'HAS_SHIELD'}     = '8'  ; # Used
$constants{'ALWAYS_TRUE'}    = '9'  ; # Used
$constants{'HAS_BOW'}        = '10' ; # Used
$constants{'HAS_SHOVEL'}     = '11' ; # Used
$constants{'HAS_SWORD'}      = '12' ; # Used
$constants{'HAS_BANJO'}      = '13' ; # Used
$constants{'LARK_DANCE'}     = '14' ; # Used
$constants{'NAVY_DANCE'}     = '15' ;
$constants{'KEEP_DANCE'}     = '16' ; # Used
$constants{'JANE_DANCE'}     = '17' ; # Used
$constants{'BOB_DANCE'}      = '18' ; # Used
$constants{'CHICKEN_1'}      = '19' ;
$constants{'CHICKEN_2'}      = '20' ;
$constants{'CHICKEN_3'}      = '21' ;
$constants{'CHICKEN_4'}      = '22' ;
$constants{'CHICKEN_5'}      = '23' ;
$constants{'SOUP_DELIVERED'} = '24' ;
$constants{'GHOST_1'}        = '25' ;
$constants{'GHOST_2'}        = '26' ;
$constants{'GHOST_3'}        = '27' ;
$constants{'GHOST_4'}        = '28' ;
$constants{'FOREST_BOSS'}    = '29' ;
$constants{'GRAVE_BOSS'}     = '30' ;
$constants{'CANNON_BOSS'}    = '31' ;
$constants{'IVAN_BOSS'}      = '32' ;

$constants{'KEY'}            = '33' ;
$constants{'LETTER'}         = '34' ; # Used
$constants{'BOB_OUT'}        = '35' ; # Used
$constants{'BANJO_TUNED'}    = '36' ; # Used
$constants{'NAVY_OUT'}       = '37' ; # Used

$constants{'POT_00'}         = '38' ; # Used
$constants{'POT_01'}         = '39' ; # Used
$constants{'POT_02'}         = '40' ; # Used
$constants{'POT_03'}         = '41' ; # Used
$constants{'POT_04'}         = '42' ; # Used
$constants{'POT_05'}         = '43' ; # Used
$constants{'POT_06'}         = '44' ; # Used
$constants{'POT_07'}         = '45' ; # Used
$constants{'POT_08'}         = '46' ; # Used
$constants{'POT_09'}         = '47' ; # Used
$constants{'POT_10'}         = '48' ; # Used
$constants{'POT_11'}         = '49' ; # Used
$constants{'POT_12'}         = '50' ; # Used
$constants{'POT_13'}         = '51' ; # Used
$constants{'POT_14'}         = '52' ; # Used
$constants{'POT_15'}         = '53' ; # Used
$constants{'POT_16'}         = '54' ; # Used
$constants{'POT_17'}         = '55' ; # Used
$constants{'POT_18'}         = '56' ; # Used
$constants{'POT_19'}         = '57' ; # Used
$constants{'POT_20'}         = '58' ; # Used
$constants{'POT_21'}         = '59' ; # Used
$constants{'POT_22'}         = '60' ; # Used
$constants{'POT_23'}         = '61' ; # Used
$constants{'POT_24'}         = '62' ; # Used
$constants{'POT_25'}         = '63' ; # Used
$constants{'POT_26'}         = '64' ; # Used
$constants{'POT_27'}         = '65' ; # Used
$constants{'POT_28'}         = '66' ; # Used
$constants{'POT_29'}         = '67' ; # Used

$constants{'BOGUS_SPOT'}   = '255'; # Used

# Rooms
$constants{'R_00'} = '00';
$constants{'R_01'} = '01';
$constants{'R_02'} = '02';
$constants{'R_03'} = '03';
$constants{'R_04'} = '04';
$constants{'R_05'} = '05';
$constants{'R_06'} = '06';
$constants{'R_07'} = '07';
$constants{'R_08'} = '08';
$constants{'R_09'} = '09';

$constants{'R_10'} = '10';
$constants{'R_11'} = '11';
$constants{'R_12'} = '12';
$constants{'R_13'} = '13';
$constants{'R_14'} = '14';
$constants{'R_15'} = '15';
$constants{'R_16'} = '16';
$constants{'R_17'} = '17';
$constants{'R_18'} = '18';
$constants{'R_19'} = '19';

$constants{'R_20'} = '20';
$constants{'R_21'} = '21';
$constants{'R_22'} = '22';
$constants{'R_23'} = '23';
$constants{'R_24'} = '24';
$constants{'R_25'} = '25';
$constants{'R_26'} = '26';
$constants{'R_27'} = '27';
$constants{'R_28'} = '28';
$constants{'R_29'} = '29';

$constants{'R_30'} = '30';
$constants{'R_31'} = '31';
$constants{'R_32'} = '32';
$constants{'R_33'} = '33';
$constants{'R_34'} = '34';
$constants{'R_35'} = '35';
$constants{'R_36'} = '36';
$constants{'R_37'} = '37';
$constants{'R_38'} = '38';
$constants{'R_39'} = '39';

$constants{'R_50'} = '50';
$constants{'R_51'} = '51';
$constants{'R_52'} = '52';
$constants{'R_53'} = '53';
$constants{'R_54'} = '54';
$constants{'R_55'} = '55';
$constants{'R_56'} = '56';
$constants{'R_57'} = '57';
$constants{'R_58'} = '58';
$constants{'R_59'} = '59';

$constants{'R_70'} = '70';
$constants{'R_71'} = '71';
$constants{'R_72'} = '72';
$constants{'R_73'} = '73';
$constants{'R_74'} = '74';
$constants{'R_75'} = '75';
$constants{'R_76'} = '76';
$constants{'R_77'} = '77';
$constants{'R_78'} = '78';
$constants{'R_79'} = '79';

# Go through the actual minifying.
my @lines = <>;
chomp(@lines);
@lines = remove_comments(@lines);
@lines = tokenize_lines(\@lines, \%constants);
@lines = remove_texts(@lines);
@lines = single_quotes_to_double(@lines);
@lines = remove_spaces(@lines);

if (not $dev_mode) {
   my %vars = populate_vars(@lines);
   @lines = tokenize_lines(\@lines, \%vars);
}

# Uncomment for each thing to go on its own line.
# Note that this is slightly more compression space.
# $lines[0] =~ s/([^\"]) ([^\"])/$1\n$2/g;
@lines = pop_text_logics(@lines);

my ($strings, $contents) = multiline_string_replace(join("\n", @lines));

sub length_in_graphemes {
    my $word = shift;
    my $length = () = $word =~ m/\X/g;
    return $length;
}

my $strings_len = length_in_graphemes($strings)-4; # -4 for '[[' and ']]'
$contents =~ s/ZTABLE_STRINGS_LEN/$strings_len/gme;
$contents =~ s/ZTABLE_STRINGS/$strings/gme;

if ($input_file ne "" and $output_file ne "") {
   open(my $src, "<:utf8", $input_file) or die "Unable to read file \"$input_file\"\n";
   open(my $dst, ">:utf8", $output_file) or die "Unable to create file \"$output_file\"\n";

   my $src_content = do { local $/; <$src> };
   $src_content =~ s/ZTABLE_STRINGS_LEN/$strings_len/gme;
   $src_content =~ s/ZTABLE_STRINGS/$strings/gme;

   close $src;

   print $dst $src_content;
   close $dst;
}

print $contents;
