#!/bin/bash
# picomake

# assumes current directory.
DIRS=""
for f in ./src ./res.p8; do
	if [ -e $f ]; then
		DIRS="$f $DIRS"
	fi
done

inotifywait -e close_write,moved_to,create -m $DIRS |
while read -r directory; do
  echo "'$directory' was changed."
  make > /dev/null
done
